/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.InlineResponse200
import io.swagger.client.model.InlineResponse400
import io.swagger.client.model.MovementInstruction
import io.swagger.client.model.MovementInstruction1
import io.swagger.client.model.RoverInfo
import io.swagger.client.model.RoverInfo1
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 201 :  (Rover created)
   *   code 400 : InlineResponse400 (Invalid request)
   * 
   * @param roverInfo Rover to create.
   */
  def apiRoversPost(roverInfo: Option[RoverInfo] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://localhost", "/api/rovers", "application/json")
      .withBody(roverInfo)
      .withSuccessResponse[Unit](201)
      .withErrorResponse[InlineResponse400](400)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : InlineResponse200 (Created)
   *   code 400 : InlineResponse400 (Invalid request)
   *   code 404 :  (Rover does not exist)
   * 
   * @param roverId 
   * @param movementInstruction Rover Id
   */
  def apiRoversRoverIdPositionsGet(roverId: Int, movementInstruction: Option[MovementInstruction] = None): ApiRequest[InlineResponse200] =
    ApiRequest[InlineResponse200](ApiMethods.GET, "https://localhost", "/api/rovers/{roverId}/positions", "application/json")
      .withBody(movementInstruction)
      .withPathParam("roverId", roverId)
      .withSuccessResponse[InlineResponse200](200)
      .withErrorResponse[InlineResponse400](400)
      .withErrorResponse[Unit](404)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : InlineResponse200 (Position Updated)
   *   code 400 : InlineResponse400 (Invalid request)
   *   code 404 :  (Rover does not exist)
   * 
   * @param roverId 
   * @param movementInstruction Movement instruction
   */
  def apiRoversRoverIdPositionsPut(roverId: Int, movementInstruction: Option[MovementInstruction1] = None): ApiRequest[InlineResponse200] =
    ApiRequest[InlineResponse200](ApiMethods.PUT, "https://localhost", "/api/rovers/{roverId}/positions", "application/json")
      .withBody(movementInstruction)
      .withPathParam("roverId", roverId)
      .withSuccessResponse[InlineResponse200](200)
      .withErrorResponse[InlineResponse400](400)
      .withErrorResponse[Unit](404)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (Rover updated)
   *   code 400 : InlineResponse400 (Invalid request)
   *   code 404 :  (Rover does not exist)
   * 
   * @param roverId 
   * @param roverInfo Rover to update.
   */
  def apiRoversRoverIdPut(roverId: Int, roverInfo: Option[RoverInfo1] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.PUT, "https://localhost", "/api/rovers/{roverId}", "application/json")
      .withBody(roverInfo)
      .withPathParam("roverId", roverId)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[InlineResponse400](400)
      .withErrorResponse[Unit](404)
      

}

